/**
 * Pre-built Certificate Background Library
 * These are designer-made background patterns using Fabric.js objects
 * Color placeholders (PRIMARY_COLOR, SECONDARY_COLOR) are replaced at runtime
 */

export interface CertificateBackground {
  id: string;
  name: string;
  category: 'gradient' | 'ornate' | 'minimal' | 'corporate' | 'geometric';
  thumbnail: string;
  objects: object[];
}

// A4 Landscape dimensions: 842 x 595 (at 72 DPI)
const CANVAS_WIDTH = 842;
const CANVAS_HEIGHT = 595;

export const BACKGROUND_CATEGORIES = [
  { id: 'all', label: 'All' },
  { id: 'gradient', label: 'Gradient' },
  { id: 'ornate', label: 'Ornate' },
  { id: 'minimal', label: 'Minimal' },
  { id: 'corporate', label: 'Corporate' },
  { id: 'geometric', label: 'Geometric' },
] as const;

export const CERTIFICATE_BACKGROUNDS: CertificateBackground[] = [
  // ===== GRADIENT BACKGROUNDS =====
  {
    id: 'gradient-radial-glow',
    name: 'Radial Glow',
    category: 'gradient',
    thumbnail: '🌅',
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: CANVAS_WIDTH,
        height: CANVAS_HEIGHT,
        fill: '#FFFEF5',
        selectable: false,
        evented: false,
      },
      {
        type: 'circle',
        left: CANVAS_WIDTH / 2,
        top: CANVAS_HEIGHT / 2,
        radius: 400,
        fill: 'PRIMARY_COLOR_LIGHT',
        opacity: 0.15,
        originX: 'center',
        originY: 'center',
        selectable: false,
        evented: false,
      },
      {
        type: 'circle',
        left: CANVAS_WIDTH / 2,
        top: CANVAS_HEIGHT / 2,
        radius: 250,
        fill: 'PRIMARY_COLOR',
        opacity: 0.08,
        originX: 'center',
        originY: 'center',
        selectable: false,
        evented: false,
      },
    ],
  },
  {
    id: 'gradient-corner-fade',
    name: 'Corner Fade',
    category: 'gradient',
    thumbnail: '🎨',
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: CANVAS_WIDTH,
        height: CANVAS_HEIGHT,
        fill: '#FFFFFF',
        selectable: false,
        evented: false,
      },
      {
        type: 'circle',
        left: 0,
        top: 0,
        radius: 300,
        fill: 'PRIMARY_COLOR',
        opacity: 0.12,
        originX: 'center',
        originY: 'center',
        selectable: false,
        evented: false,
      },
      {
        type: 'circle',
        left: CANVAS_WIDTH,
        top: CANVAS_HEIGHT,
        radius: 250,
        fill: 'SECONDARY_COLOR',
        opacity: 0.1,
        originX: 'center',
        originY: 'center',
        selectable: false,
        evented: false,
      },
    ],
  },
  {
    id: 'gradient-diagonal',
    name: 'Diagonal Sweep',
    category: 'gradient',
    thumbnail: '🌈',
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: CANVAS_WIDTH,
        height: CANVAS_HEIGHT,
        fill: '#FAFAFA',
        selectable: false,
        evented: false,
      },
      {
        type: 'polygon',
        points: [
          { x: 0, y: CANVAS_HEIGHT },
          { x: CANVAS_WIDTH, y: CANVAS_HEIGHT * 0.4 },
          { x: CANVAS_WIDTH, y: CANVAS_HEIGHT },
        ],
        fill: 'PRIMARY_COLOR',
        opacity: 0.08,
        selectable: false,
        evented: false,
      },
      {
        type: 'polygon',
        points: [
          { x: 0, y: CANVAS_HEIGHT },
          { x: CANVAS_WIDTH, y: CANVAS_HEIGHT * 0.6 },
          { x: CANVAS_WIDTH, y: CANVAS_HEIGHT },
        ],
        fill: 'SECONDARY_COLOR',
        opacity: 0.05,
        selectable: false,
        evented: false,
      },
    ],
  },

  // ===== ORNATE BACKGROUNDS =====
  {
    id: 'ornate-double-border',
    name: 'Classic Double Border',
    category: 'ornate',
    thumbnail: '🏛️',
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: CANVAS_WIDTH,
        height: CANVAS_HEIGHT,
        fill: '#FFFEF8',
        selectable: false,
        evented: false,
      },
      // Outer border
      {
        type: 'rect',
        left: 20,
        top: 20,
        width: CANVAS_WIDTH - 40,
        height: CANVAS_HEIGHT - 40,
        fill: 'transparent',
        stroke: 'PRIMARY_COLOR',
        strokeWidth: 3,
        selectable: false,
        evented: false,
      },
      // Inner border
      {
        type: 'rect',
        left: 35,
        top: 35,
        width: CANVAS_WIDTH - 70,
        height: CANVAS_HEIGHT - 70,
        fill: 'transparent',
        stroke: 'SECONDARY_COLOR',
        strokeWidth: 1.5,
        selectable: false,
        evented: false,
      },
      // Corner flourishes
      {
        type: 'circle',
        left: 35,
        top: 35,
        radius: 8,
        fill: 'SECONDARY_COLOR',
        selectable: false,
        evented: false,
      },
      {
        type: 'circle',
        left: CANVAS_WIDTH - 35,
        top: 35,
        radius: 8,
        fill: 'SECONDARY_COLOR',
        originX: 'right',
        selectable: false,
        evented: false,
      },
      {
        type: 'circle',
        left: 35,
        top: CANVAS_HEIGHT - 35,
        radius: 8,
        fill: 'SECONDARY_COLOR',
        originY: 'bottom',
        selectable: false,
        evented: false,
      },
      {
        type: 'circle',
        left: CANVAS_WIDTH - 35,
        top: CANVAS_HEIGHT - 35,
        radius: 8,
        fill: 'SECONDARY_COLOR',
        originX: 'right',
        originY: 'bottom',
        selectable: false,
        evented: false,
      },
    ],
  },
  {
    id: 'ornate-elegant-frame',
    name: 'Elegant Frame',
    category: 'ornate',
    thumbnail: '✨',
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: CANVAS_WIDTH,
        height: CANVAS_HEIGHT,
        fill: '#FEFDFB',
        selectable: false,
        evented: false,
      },
      // Top decorative band
      {
        type: 'rect',
        left: 50,
        top: 30,
        width: CANVAS_WIDTH - 100,
        height: 6,
        fill: 'PRIMARY_COLOR',
        selectable: false,
        evented: false,
      },
      {
        type: 'rect',
        left: 50,
        top: 40,
        width: CANVAS_WIDTH - 100,
        height: 2,
        fill: 'SECONDARY_COLOR',
        selectable: false,
        evented: false,
      },
      // Bottom decorative band
      {
        type: 'rect',
        left: 50,
        top: CANVAS_HEIGHT - 36,
        width: CANVAS_WIDTH - 100,
        height: 6,
        fill: 'PRIMARY_COLOR',
        selectable: false,
        evented: false,
      },
      {
        type: 'rect',
        left: 50,
        top: CANVAS_HEIGHT - 42,
        width: CANVAS_WIDTH - 100,
        height: 2,
        fill: 'SECONDARY_COLOR',
        selectable: false,
        evented: false,
      },
      // Side lines
      {
        type: 'line',
        x1: 30,
        y1: 50,
        x2: 30,
        y2: CANVAS_HEIGHT - 50,
        stroke: 'PRIMARY_COLOR',
        strokeWidth: 2,
        selectable: false,
        evented: false,
      },
      {
        type: 'line',
        x1: CANVAS_WIDTH - 30,
        y1: 50,
        x2: CANVAS_WIDTH - 30,
        y2: CANVAS_HEIGHT - 50,
        stroke: 'PRIMARY_COLOR',
        strokeWidth: 2,
        selectable: false,
        evented: false,
      },
    ],
  },
  {
    id: 'ornate-seal-corners',
    name: 'Seal & Corners',
    category: 'ornate',
    thumbnail: '🎖️',
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: CANVAS_WIDTH,
        height: CANVAS_HEIGHT,
        fill: '#FFFEF5',
        selectable: false,
        evented: false,
      },
      // Border
      {
        type: 'rect',
        left: 25,
        top: 25,
        width: CANVAS_WIDTH - 50,
        height: CANVAS_HEIGHT - 50,
        fill: 'transparent',
        stroke: 'PRIMARY_COLOR',
        strokeWidth: 2,
        selectable: false,
        evented: false,
      },
      // Corner decorations (L shapes)
      // Top left
      {
        type: 'rect',
        left: 15,
        top: 15,
        width: 60,
        height: 4,
        fill: 'SECONDARY_COLOR',
        selectable: false,
        evented: false,
      },
      {
        type: 'rect',
        left: 15,
        top: 15,
        width: 4,
        height: 60,
        fill: 'SECONDARY_COLOR',
        selectable: false,
        evented: false,
      },
      // Top right
      {
        type: 'rect',
        left: CANVAS_WIDTH - 75,
        top: 15,
        width: 60,
        height: 4,
        fill: 'SECONDARY_COLOR',
        selectable: false,
        evented: false,
      },
      {
        type: 'rect',
        left: CANVAS_WIDTH - 19,
        top: 15,
        width: 4,
        height: 60,
        fill: 'SECONDARY_COLOR',
        selectable: false,
        evented: false,
      },
      // Bottom left
      {
        type: 'rect',
        left: 15,
        top: CANVAS_HEIGHT - 19,
        width: 60,
        height: 4,
        fill: 'SECONDARY_COLOR',
        selectable: false,
        evented: false,
      },
      {
        type: 'rect',
        left: 15,
        top: CANVAS_HEIGHT - 75,
        width: 4,
        height: 60,
        fill: 'SECONDARY_COLOR',
        selectable: false,
        evented: false,
      },
      // Bottom right
      {
        type: 'rect',
        left: CANVAS_WIDTH - 75,
        top: CANVAS_HEIGHT - 19,
        width: 60,
        height: 4,
        fill: 'SECONDARY_COLOR',
        selectable: false,
        evented: false,
      },
      {
        type: 'rect',
        left: CANVAS_WIDTH - 19,
        top: CANVAS_HEIGHT - 75,
        width: 4,
        height: 60,
        fill: 'SECONDARY_COLOR',
        selectable: false,
        evented: false,
      },
    ],
  },

  // ===== MINIMAL BACKGROUNDS =====
  {
    id: 'minimal-clean',
    name: 'Clean White',
    category: 'minimal',
    thumbnail: '⬜',
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: CANVAS_WIDTH,
        height: CANVAS_HEIGHT,
        fill: '#FFFFFF',
        selectable: false,
        evented: false,
      },
      {
        type: 'rect',
        left: 40,
        top: 40,
        width: CANVAS_WIDTH - 80,
        height: CANVAS_HEIGHT - 80,
        fill: 'transparent',
        stroke: 'PRIMARY_COLOR',
        strokeWidth: 1,
        opacity: 0.3,
        selectable: false,
        evented: false,
      },
    ],
  },
  {
    id: 'minimal-accent-line',
    name: 'Accent Line',
    category: 'minimal',
    thumbnail: '─',
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: CANVAS_WIDTH,
        height: CANVAS_HEIGHT,
        fill: '#FFFFFF',
        selectable: false,
        evented: false,
      },
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 8,
        height: CANVAS_HEIGHT,
        fill: 'PRIMARY_COLOR',
        selectable: false,
        evented: false,
      },
      {
        type: 'rect',
        left: 8,
        top: 0,
        width: 3,
        height: CANVAS_HEIGHT,
        fill: 'SECONDARY_COLOR',
        selectable: false,
        evented: false,
      },
    ],
  },
  {
    id: 'minimal-bottom-band',
    name: 'Bottom Band',
    category: 'minimal',
    thumbnail: '▁',
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: CANVAS_WIDTH,
        height: CANVAS_HEIGHT,
        fill: '#FFFFFF',
        selectable: false,
        evented: false,
      },
      {
        type: 'rect',
        left: 0,
        top: CANVAS_HEIGHT - 25,
        width: CANVAS_WIDTH,
        height: 25,
        fill: 'PRIMARY_COLOR',
        selectable: false,
        evented: false,
      },
    ],
  },

  // ===== CORPORATE BACKGROUNDS =====
  {
    id: 'corporate-header-band',
    name: 'Header Band',
    category: 'corporate',
    thumbnail: '▬',
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: CANVAS_WIDTH,
        height: CANVAS_HEIGHT,
        fill: '#FFFFFF',
        selectable: false,
        evented: false,
      },
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: CANVAS_WIDTH,
        height: 80,
        fill: 'PRIMARY_COLOR',
        selectable: false,
        evented: false,
      },
      {
        type: 'rect',
        left: 0,
        top: 80,
        width: CANVAS_WIDTH,
        height: 6,
        fill: 'SECONDARY_COLOR',
        selectable: false,
        evented: false,
      },
    ],
  },
  {
    id: 'corporate-footer-accent',
    name: 'Footer Accent',
    category: 'corporate',
    thumbnail: '▂',
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: CANVAS_WIDTH,
        height: CANVAS_HEIGHT,
        fill: '#FAFAFA',
        selectable: false,
        evented: false,
      },
      {
        type: 'rect',
        left: 0,
        top: CANVAS_HEIGHT - 50,
        width: CANVAS_WIDTH,
        height: 50,
        fill: 'PRIMARY_COLOR',
        selectable: false,
        evented: false,
      },
      {
        type: 'rect',
        left: 0,
        top: CANVAS_HEIGHT - 56,
        width: CANVAS_WIDTH,
        height: 6,
        fill: 'SECONDARY_COLOR',
        selectable: false,
        evented: false,
      },
    ],
  },
  {
    id: 'corporate-side-stripe',
    name: 'Side Stripe',
    category: 'corporate',
    thumbnail: '▌',
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: CANVAS_WIDTH,
        height: CANVAS_HEIGHT,
        fill: '#FFFFFF',
        selectable: false,
        evented: false,
      },
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 60,
        height: CANVAS_HEIGHT,
        fill: 'PRIMARY_COLOR',
        selectable: false,
        evented: false,
      },
      {
        type: 'rect',
        left: 60,
        top: 0,
        width: 4,
        height: CANVAS_HEIGHT,
        fill: 'SECONDARY_COLOR',
        selectable: false,
        evented: false,
      },
    ],
  },

  // ===== GEOMETRIC BACKGROUNDS =====
  {
    id: 'geometric-diamond',
    name: 'Diamond Pattern',
    category: 'geometric',
    thumbnail: '◇',
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: CANVAS_WIDTH,
        height: CANVAS_HEIGHT,
        fill: '#FFFFFF',
        selectable: false,
        evented: false,
      },
      // Decorative diamonds in corners
      {
        type: 'polygon',
        points: [
          { x: 30, y: 0 },
          { x: 60, y: 30 },
          { x: 30, y: 60 },
          { x: 0, y: 30 },
        ],
        left: 20,
        top: 20,
        fill: 'PRIMARY_COLOR',
        opacity: 0.15,
        selectable: false,
        evented: false,
      },
      {
        type: 'polygon',
        points: [
          { x: 20, y: 0 },
          { x: 40, y: 20 },
          { x: 20, y: 40 },
          { x: 0, y: 20 },
        ],
        left: CANVAS_WIDTH - 70,
        top: 25,
        fill: 'SECONDARY_COLOR',
        opacity: 0.2,
        selectable: false,
        evented: false,
      },
      {
        type: 'polygon',
        points: [
          { x: 25, y: 0 },
          { x: 50, y: 25 },
          { x: 25, y: 50 },
          { x: 0, y: 25 },
        ],
        left: CANVAS_WIDTH - 80,
        top: CANVAS_HEIGHT - 80,
        fill: 'PRIMARY_COLOR',
        opacity: 0.12,
        selectable: false,
        evented: false,
      },
    ],
  },
  {
    id: 'geometric-circles',
    name: 'Circle Accents',
    category: 'geometric',
    thumbnail: '◎',
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: CANVAS_WIDTH,
        height: CANVAS_HEIGHT,
        fill: '#FAFAFA',
        selectable: false,
        evented: false,
      },
      {
        type: 'circle',
        left: 60,
        top: 60,
        radius: 40,
        fill: 'transparent',
        stroke: 'PRIMARY_COLOR',
        strokeWidth: 2,
        opacity: 0.2,
        selectable: false,
        evented: false,
      },
      {
        type: 'circle',
        left: 90,
        top: 90,
        radius: 25,
        fill: 'PRIMARY_COLOR',
        opacity: 0.1,
        selectable: false,
        evented: false,
      },
      {
        type: 'circle',
        left: CANVAS_WIDTH - 80,
        top: CANVAS_HEIGHT - 80,
        radius: 50,
        fill: 'transparent',
        stroke: 'SECONDARY_COLOR',
        strokeWidth: 2,
        opacity: 0.2,
        selectable: false,
        evented: false,
      },
    ],
  },
  {
    id: 'geometric-lines',
    name: 'Line Art',
    category: 'geometric',
    thumbnail: '╱',
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: CANVAS_WIDTH,
        height: CANVAS_HEIGHT,
        fill: '#FFFFFF',
        selectable: false,
        evented: false,
      },
      // Diagonal lines in top right
      {
        type: 'line',
        x1: CANVAS_WIDTH - 100,
        y1: 0,
        x2: CANVAS_WIDTH,
        y2: 100,
        stroke: 'PRIMARY_COLOR',
        strokeWidth: 2,
        opacity: 0.15,
        selectable: false,
        evented: false,
      },
      {
        type: 'line',
        x1: CANVAS_WIDTH - 70,
        y1: 0,
        x2: CANVAS_WIDTH,
        y2: 70,
        stroke: 'PRIMARY_COLOR',
        strokeWidth: 2,
        opacity: 0.1,
        selectable: false,
        evented: false,
      },
      {
        type: 'line',
        x1: CANVAS_WIDTH - 40,
        y1: 0,
        x2: CANVAS_WIDTH,
        y2: 40,
        stroke: 'SECONDARY_COLOR',
        strokeWidth: 2,
        opacity: 0.15,
        selectable: false,
        evented: false,
      },
      // Bottom left accent
      {
        type: 'line',
        x1: 0,
        y1: CANVAS_HEIGHT - 60,
        x2: 60,
        y2: CANVAS_HEIGHT,
        stroke: 'PRIMARY_COLOR',
        strokeWidth: 2,
        opacity: 0.15,
        selectable: false,
        evented: false,
      },
    ],
  },
];
