/**
 * Pre-built Certificate Content Layouts
 * These define the positioning of text elements and placeholders
 * Text content uses placeholder syntax like {recipient_name}, {event_name}, etc.
 */

export interface CertificateContentLayout {
  id: string;
  name: string;
  style: 'elegant' | 'modern' | 'corporate' | 'creative' | 'academic';
  certificateType: 'Completion' | 'Achievement' | 'Participation' | 'Excellence' | 'Appreciation';
  objects: object[];
}

// A4 Landscape dimensions: 842 x 595 (at 72 DPI)
const CANVAS_WIDTH = 842;
const CANVAS_HEIGHT = 595;
const CENTER_X = CANVAS_WIDTH / 2;

export const LAYOUT_STYLES = [
  { id: 'elegant', label: 'Elegant & Classic', description: 'Traditional formal design with serif fonts' },
  { id: 'modern', label: 'Modern & Minimal', description: 'Clean lines with contemporary typography' },
  { id: 'corporate', label: 'Corporate Professional', description: 'Business-focused with structured layout' },
  { id: 'creative', label: 'Creative & Artistic', description: 'Unique design with artistic elements' },
  { id: 'academic', label: 'Academic & Traditional', description: 'Classic educational certificate style' },
] as const;

export const CERTIFICATE_TYPES = [
  { value: 'Completion', label: 'Certificate of Completion' },
  { value: 'Achievement', label: 'Certificate of Achievement' },
  { value: 'Participation', label: 'Certificate of Participation' },
  { value: 'Excellence', label: 'Certificate of Excellence' },
  { value: 'Appreciation', label: 'Certificate of Appreciation' },
] as const;

export const CERTIFICATE_CONTENT_LAYOUTS: CertificateContentLayout[] = [
  // ===== ELEGANT LAYOUTS =====
  {
    id: 'elegant-completion',
    name: 'Elegant Completion',
    style: 'elegant',
    certificateType: 'Completion',
    objects: [
      // Title
      {
        type: 'textbox',
        left: CENTER_X,
        top: 120,
        width: 600,
        text: 'Certificate of Completion',
        fontSize: 42,
        fontWeight: 'bold',
        fontFamily: 'Georgia',
        fill: 'PRIMARY_COLOR',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      // Subtitle
      {
        type: 'textbox',
        left: CENTER_X,
        top: 175,
        width: 500,
        text: 'This is to certify that',
        fontSize: 18,
        fontFamily: 'Georgia',
        fill: 'TEXT_MUTED',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      // Recipient name
      {
        type: 'textbox',
        left: CENTER_X,
        top: 220,
        width: 600,
        text: '{recipient_name}',
        fontSize: 36,
        fontWeight: 'bold',
        fontFamily: 'Georgia',
        fill: 'TEXT_COLOR',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      // Description line
      {
        type: 'textbox',
        left: CENTER_X,
        top: 280,
        width: 600,
        text: 'has successfully completed the requirements of',
        fontSize: 16,
        fontFamily: 'Georgia',
        fill: 'TEXT_MUTED',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      // Event name
      {
        type: 'textbox',
        left: CENTER_X,
        top: 320,
        width: 600,
        text: '{event_name}',
        fontSize: 28,
        fontWeight: 'bold',
        fontFamily: 'Georgia',
        fill: 'PRIMARY_COLOR',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      // Date
      {
        type: 'textbox',
        left: CENTER_X,
        top: 380,
        width: 400,
        text: 'Issued on {issue_date}',
        fontSize: 14,
        fontFamily: 'Georgia',
        fill: 'TEXT_MUTED',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      // Signature line
      {
        type: 'line',
        x1: CENTER_X - 100,
        y1: 470,
        x2: CENTER_X + 100,
        y2: 470,
        stroke: 'TEXT_MUTED',
        strokeWidth: 1,
        selectable: false,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 480,
        width: 200,
        text: 'Authorized Signature',
        fontSize: 12,
        fontFamily: 'Georgia',
        fill: 'TEXT_MUTED',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      // Certificate ID
      {
        type: 'textbox',
        left: CENTER_X,
        top: 540,
        width: 300,
        text: 'Certificate ID: {certificate_id}',
        fontSize: 10,
        fontFamily: 'Arial',
        fill: 'TEXT_MUTED',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      // QR Code placeholder
      {
        type: 'rect',
        left: CANVAS_WIDTH - 100,
        top: CANVAS_HEIGHT - 100,
        width: 60,
        height: 60,
        fill: '#F3F4F6',
        stroke: 'TEXT_MUTED',
        strokeWidth: 1,
        selectable: true,
        data: { isPlaceholder: true, placeholderType: 'qr' },
      },
    ],
  },
  {
    id: 'elegant-achievement',
    name: 'Elegant Achievement',
    style: 'elegant',
    certificateType: 'Achievement',
    objects: [
      {
        type: 'textbox',
        left: CENTER_X,
        top: 110,
        width: 600,
        text: 'Certificate of Achievement',
        fontSize: 44,
        fontWeight: 'bold',
        fontFamily: 'Georgia',
        fill: 'PRIMARY_COLOR',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 170,
        width: 500,
        text: 'Proudly presented to',
        fontSize: 18,
        fontFamily: 'Georgia',
        fill: 'TEXT_MUTED',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 215,
        width: 600,
        text: '{recipient_name}',
        fontSize: 38,
        fontWeight: 'bold',
        fontFamily: 'Georgia',
        fill: 'TEXT_COLOR',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 275,
        width: 600,
        text: 'for outstanding achievement in',
        fontSize: 16,
        fontFamily: 'Georgia',
        fill: 'TEXT_MUTED',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 315,
        width: 600,
        text: '{event_name}',
        fontSize: 28,
        fontWeight: 'bold',
        fontFamily: 'Georgia',
        fill: 'PRIMARY_COLOR',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 375,
        width: 400,
        text: '{issue_date}',
        fontSize: 14,
        fontFamily: 'Georgia',
        fill: 'TEXT_MUTED',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'line',
        x1: CENTER_X - 100,
        y1: 470,
        x2: CENTER_X + 100,
        y2: 470,
        stroke: 'TEXT_MUTED',
        strokeWidth: 1,
        selectable: false,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 480,
        width: 200,
        text: 'Authorized Signature',
        fontSize: 12,
        fontFamily: 'Georgia',
        fill: 'TEXT_MUTED',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 540,
        width: 300,
        text: 'ID: {certificate_id}',
        fontSize: 10,
        fontFamily: 'Arial',
        fill: 'TEXT_MUTED',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'rect',
        left: CANVAS_WIDTH - 100,
        top: CANVAS_HEIGHT - 100,
        width: 60,
        height: 60,
        fill: '#F3F4F6',
        stroke: 'TEXT_MUTED',
        strokeWidth: 1,
        selectable: true,
        data: { isPlaceholder: true, placeholderType: 'qr' },
      },
    ],
  },

  // ===== MODERN LAYOUTS =====
  {
    id: 'modern-completion',
    name: 'Modern Completion',
    style: 'modern',
    certificateType: 'Completion',
    objects: [
      // Accent bar
      {
        type: 'rect',
        left: CENTER_X - 50,
        top: 100,
        width: 100,
        height: 4,
        fill: 'PRIMARY_COLOR',
        originX: 'center',
        selectable: false,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 120,
        width: 600,
        text: 'CERTIFICATE OF COMPLETION',
        fontSize: 32,
        fontWeight: 'bold',
        fontFamily: 'Arial',
        fill: 'TEXT_COLOR',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 200,
        width: 600,
        text: '{recipient_name}',
        fontSize: 40,
        fontWeight: 'bold',
        fontFamily: 'Arial',
        fill: 'PRIMARY_COLOR',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 270,
        width: 600,
        text: 'has successfully completed',
        fontSize: 16,
        fontFamily: 'Arial',
        fill: 'TEXT_MUTED',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 310,
        width: 600,
        text: '{event_name}',
        fontSize: 26,
        fontWeight: 'bold',
        fontFamily: 'Arial',
        fill: 'TEXT_COLOR',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 380,
        width: 400,
        text: '{issue_date}',
        fontSize: 14,
        fontFamily: 'Arial',
        fill: 'TEXT_MUTED',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'rect',
        left: CENTER_X - 60,
        top: 450,
        width: 120,
        height: 2,
        fill: 'TEXT_MUTED',
        originX: 'center',
        selectable: false,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 460,
        width: 200,
        text: 'Signature',
        fontSize: 11,
        fontFamily: 'Arial',
        fill: 'TEXT_MUTED',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 530,
        width: 300,
        text: '{certificate_id}',
        fontSize: 10,
        fontFamily: 'Arial',
        fill: 'TEXT_MUTED',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'rect',
        left: CANVAS_WIDTH - 100,
        top: CANVAS_HEIGHT - 100,
        width: 60,
        height: 60,
        fill: '#F3F4F6',
        stroke: 'TEXT_MUTED',
        strokeWidth: 1,
        selectable: true,
        data: { isPlaceholder: true, placeholderType: 'qr' },
      },
    ],
  },
  {
    id: 'modern-participation',
    name: 'Modern Participation',
    style: 'modern',
    certificateType: 'Participation',
    objects: [
      {
        type: 'rect',
        left: CENTER_X - 40,
        top: 105,
        width: 80,
        height: 3,
        fill: 'SECONDARY_COLOR',
        originX: 'center',
        selectable: false,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 125,
        width: 600,
        text: 'CERTIFICATE OF PARTICIPATION',
        fontSize: 30,
        fontWeight: 'bold',
        fontFamily: 'Arial',
        fill: 'TEXT_COLOR',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 190,
        width: 500,
        text: 'This certifies that',
        fontSize: 14,
        fontFamily: 'Arial',
        fill: 'TEXT_MUTED',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 225,
        width: 600,
        text: '{recipient_name}',
        fontSize: 36,
        fontWeight: 'bold',
        fontFamily: 'Arial',
        fill: 'PRIMARY_COLOR',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 290,
        width: 600,
        text: 'participated in',
        fontSize: 14,
        fontFamily: 'Arial',
        fill: 'TEXT_MUTED',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 325,
        width: 600,
        text: '{event_name}',
        fontSize: 24,
        fontWeight: 'bold',
        fontFamily: 'Arial',
        fill: 'TEXT_COLOR',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 390,
        width: 400,
        text: 'Date: {issue_date}',
        fontSize: 13,
        fontFamily: 'Arial',
        fill: 'TEXT_MUTED',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'rect',
        left: CENTER_X - 50,
        top: 455,
        width: 100,
        height: 2,
        fill: 'TEXT_MUTED',
        originX: 'center',
        selectable: false,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 465,
        width: 200,
        text: 'Organizer',
        fontSize: 11,
        fontFamily: 'Arial',
        fill: 'TEXT_MUTED',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 535,
        width: 300,
        text: 'Ref: {certificate_id}',
        fontSize: 9,
        fontFamily: 'Arial',
        fill: 'TEXT_MUTED',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'rect',
        left: CANVAS_WIDTH - 100,
        top: CANVAS_HEIGHT - 100,
        width: 60,
        height: 60,
        fill: '#F3F4F6',
        stroke: 'TEXT_MUTED',
        strokeWidth: 1,
        selectable: true,
        data: { isPlaceholder: true, placeholderType: 'qr' },
      },
    ],
  },

  // ===== CORPORATE LAYOUTS =====
  {
    id: 'corporate-completion',
    name: 'Corporate Completion',
    style: 'corporate',
    certificateType: 'Completion',
    objects: [
      {
        type: 'textbox',
        left: CENTER_X,
        top: 130,
        width: 600,
        text: 'Certificate of Completion',
        fontSize: 36,
        fontWeight: 'bold',
        fontFamily: 'Arial',
        fill: 'PRIMARY_COLOR',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'rect',
        left: CENTER_X - 200,
        top: 180,
        width: 400,
        height: 2,
        fill: 'SECONDARY_COLOR',
        originX: 'center',
        selectable: false,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 210,
        width: 600,
        text: '{recipient_name}',
        fontSize: 32,
        fontWeight: 'bold',
        fontFamily: 'Arial',
        fill: 'TEXT_COLOR',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 270,
        width: 600,
        text: 'has completed the program',
        fontSize: 16,
        fontFamily: 'Arial',
        fill: 'TEXT_MUTED',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 310,
        width: 600,
        text: '{event_name}',
        fontSize: 24,
        fontWeight: 'bold',
        fontFamily: 'Arial',
        fill: 'PRIMARY_COLOR',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 380,
        width: 400,
        text: 'Issued: {issue_date}',
        fontSize: 13,
        fontFamily: 'Arial',
        fill: 'TEXT_MUTED',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'line',
        x1: 200,
        y1: 480,
        x2: 350,
        y2: 480,
        stroke: 'TEXT_MUTED',
        strokeWidth: 1,
        selectable: false,
      },
      {
        type: 'textbox',
        left: 275,
        top: 490,
        width: 150,
        text: 'Director',
        fontSize: 11,
        fontFamily: 'Arial',
        fill: 'TEXT_MUTED',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'line',
        x1: 492,
        y1: 480,
        x2: 642,
        y2: 480,
        stroke: 'TEXT_MUTED',
        strokeWidth: 1,
        selectable: false,
      },
      {
        type: 'textbox',
        left: 567,
        top: 490,
        width: 150,
        text: 'Program Lead',
        fontSize: 11,
        fontFamily: 'Arial',
        fill: 'TEXT_MUTED',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 545,
        width: 300,
        text: 'Certificate No: {certificate_id}',
        fontSize: 10,
        fontFamily: 'Arial',
        fill: 'TEXT_MUTED',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'rect',
        left: CANVAS_WIDTH - 100,
        top: CANVAS_HEIGHT - 100,
        width: 60,
        height: 60,
        fill: '#F3F4F6',
        stroke: 'TEXT_MUTED',
        strokeWidth: 1,
        selectable: true,
        data: { isPlaceholder: true, placeholderType: 'qr' },
      },
    ],
  },
  {
    id: 'corporate-excellence',
    name: 'Corporate Excellence',
    style: 'corporate',
    certificateType: 'Excellence',
    objects: [
      {
        type: 'textbox',
        left: CENTER_X,
        top: 120,
        width: 600,
        text: 'Certificate of Excellence',
        fontSize: 38,
        fontWeight: 'bold',
        fontFamily: 'Arial',
        fill: 'PRIMARY_COLOR',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'rect',
        left: CENTER_X - 180,
        top: 175,
        width: 360,
        height: 2,
        fill: 'SECONDARY_COLOR',
        originX: 'center',
        selectable: false,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 205,
        width: 600,
        text: '{recipient_name}',
        fontSize: 34,
        fontWeight: 'bold',
        fontFamily: 'Arial',
        fill: 'TEXT_COLOR',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 270,
        width: 600,
        text: 'has demonstrated excellence in',
        fontSize: 15,
        fontFamily: 'Arial',
        fill: 'TEXT_MUTED',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 310,
        width: 600,
        text: '{event_name}',
        fontSize: 26,
        fontWeight: 'bold',
        fontFamily: 'Arial',
        fill: 'PRIMARY_COLOR',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 380,
        width: 400,
        text: 'Awarded on {issue_date}',
        fontSize: 13,
        fontFamily: 'Arial',
        fill: 'TEXT_MUTED',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'line',
        x1: CENTER_X - 80,
        y1: 475,
        x2: CENTER_X + 80,
        y2: 475,
        stroke: 'TEXT_MUTED',
        strokeWidth: 1,
        selectable: false,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 485,
        width: 200,
        text: 'Executive Director',
        fontSize: 11,
        fontFamily: 'Arial',
        fill: 'TEXT_MUTED',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 545,
        width: 300,
        text: 'Ref: {certificate_id}',
        fontSize: 10,
        fontFamily: 'Arial',
        fill: 'TEXT_MUTED',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'rect',
        left: CANVAS_WIDTH - 100,
        top: CANVAS_HEIGHT - 100,
        width: 60,
        height: 60,
        fill: '#F3F4F6',
        stroke: 'TEXT_MUTED',
        strokeWidth: 1,
        selectable: true,
        data: { isPlaceholder: true, placeholderType: 'qr' },
      },
    ],
  },

  // ===== CREATIVE LAYOUTS =====
  {
    id: 'creative-appreciation',
    name: 'Creative Appreciation',
    style: 'creative',
    certificateType: 'Appreciation',
    objects: [
      {
        type: 'textbox',
        left: CENTER_X,
        top: 100,
        width: 600,
        text: '✦ Certificate of Appreciation ✦',
        fontSize: 34,
        fontWeight: 'bold',
        fontFamily: 'Georgia',
        fill: 'PRIMARY_COLOR',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 160,
        width: 500,
        text: 'With sincere gratitude to',
        fontSize: 16,
        fontFamily: 'Georgia',
        fontStyle: 'italic',
        fill: 'TEXT_MUTED',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 205,
        width: 600,
        text: '{recipient_name}',
        fontSize: 40,
        fontWeight: 'bold',
        fontFamily: 'Georgia',
        fill: 'SECONDARY_COLOR',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 275,
        width: 600,
        text: 'for valuable contribution to',
        fontSize: 15,
        fontFamily: 'Georgia',
        fontStyle: 'italic',
        fill: 'TEXT_MUTED',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 315,
        width: 600,
        text: '{event_name}',
        fontSize: 26,
        fontWeight: 'bold',
        fontFamily: 'Georgia',
        fill: 'PRIMARY_COLOR',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 385,
        width: 400,
        text: '{issue_date}',
        fontSize: 14,
        fontFamily: 'Georgia',
        fill: 'TEXT_MUTED',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'line',
        x1: CENTER_X - 100,
        y1: 475,
        x2: CENTER_X + 100,
        y2: 475,
        stroke: 'SECONDARY_COLOR',
        strokeWidth: 1,
        selectable: false,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 485,
        width: 200,
        text: 'With Thanks',
        fontSize: 12,
        fontFamily: 'Georgia',
        fontStyle: 'italic',
        fill: 'TEXT_MUTED',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 540,
        width: 300,
        text: '{certificate_id}',
        fontSize: 10,
        fontFamily: 'Arial',
        fill: 'TEXT_MUTED',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'rect',
        left: CANVAS_WIDTH - 100,
        top: CANVAS_HEIGHT - 100,
        width: 60,
        height: 60,
        fill: '#F3F4F6',
        stroke: 'TEXT_MUTED',
        strokeWidth: 1,
        selectable: true,
        data: { isPlaceholder: true, placeholderType: 'qr' },
      },
    ],
  },

  // ===== ACADEMIC LAYOUTS =====
  {
    id: 'academic-completion',
    name: 'Academic Completion',
    style: 'academic',
    certificateType: 'Completion',
    objects: [
      {
        type: 'textbox',
        left: CENTER_X,
        top: 110,
        width: 600,
        text: 'Certificate of Completion',
        fontSize: 40,
        fontWeight: 'bold',
        fontFamily: 'Times New Roman',
        fill: 'PRIMARY_COLOR',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 170,
        width: 500,
        text: 'This is to certify that',
        fontSize: 16,
        fontFamily: 'Times New Roman',
        fontStyle: 'italic',
        fill: 'TEXT_MUTED',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 210,
        width: 600,
        text: '{recipient_name}',
        fontSize: 36,
        fontWeight: 'bold',
        fontFamily: 'Times New Roman',
        fill: 'TEXT_COLOR',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 270,
        width: 600,
        text: 'has successfully completed the curriculum for',
        fontSize: 15,
        fontFamily: 'Times New Roman',
        fill: 'TEXT_MUTED',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 310,
        width: 600,
        text: '{event_name}',
        fontSize: 28,
        fontWeight: 'bold',
        fontFamily: 'Times New Roman',
        fill: 'PRIMARY_COLOR',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 380,
        width: 400,
        text: 'Conferred on {issue_date}',
        fontSize: 14,
        fontFamily: 'Times New Roman',
        fontStyle: 'italic',
        fill: 'TEXT_MUTED',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'line',
        x1: 180,
        y1: 480,
        x2: 320,
        y2: 480,
        stroke: 'TEXT_MUTED',
        strokeWidth: 1,
        selectable: false,
      },
      {
        type: 'textbox',
        left: 250,
        top: 490,
        width: 150,
        text: 'Dean',
        fontSize: 11,
        fontFamily: 'Times New Roman',
        fill: 'TEXT_MUTED',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'line',
        x1: 522,
        y1: 480,
        x2: 662,
        y2: 480,
        stroke: 'TEXT_MUTED',
        strokeWidth: 1,
        selectable: false,
      },
      {
        type: 'textbox',
        left: 592,
        top: 490,
        width: 150,
        text: 'Registrar',
        fontSize: 11,
        fontFamily: 'Times New Roman',
        fill: 'TEXT_MUTED',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'textbox',
        left: CENTER_X,
        top: 545,
        width: 300,
        text: 'Registration No: {certificate_id}',
        fontSize: 10,
        fontFamily: 'Arial',
        fill: 'TEXT_MUTED',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
      },
      {
        type: 'rect',
        left: CANVAS_WIDTH - 100,
        top: CANVAS_HEIGHT - 100,
        width: 60,
        height: 60,
        fill: '#F3F4F6',
        stroke: 'TEXT_MUTED',
        strokeWidth: 1,
        selectable: true,
        data: { isPlaceholder: true, placeholderType: 'qr' },
      },
    ],
  },
];

/**
 * Get layout by style and certificate type
 */
export function getLayoutByStyleAndType(
  style: string,
  certificateType: string
): CertificateContentLayout | undefined {
  return CERTIFICATE_CONTENT_LAYOUTS.find(
    layout => layout.style === style && layout.certificateType === certificateType
  );
}

/**
 * Get all layouts for a given style
 */
export function getLayoutsByStyle(style: string): CertificateContentLayout[] {
  return CERTIFICATE_CONTENT_LAYOUTS.filter(layout => layout.style === style);
}
