// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = 'https://oijrbovmdimgxlvkmybx.supabase.co';
const SUPABASE_PUBLISHABLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9panJib3ZtZGltZ3hsdmtteWJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY2NzYwOTksImV4cCI6MjA4MjI1MjA5OX0.Dfx_0PJlKFQ7CGDOye9JCllLpf4-A4gVUiqWZrzgmT0';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// We intentionally create an untyped Supabase client here so that
// features still using legacy table names (e.g. "events", "services")
// can compile while we gradually migrate them to the new schema.
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});